server.port=8080
jwt.secret = 8dae84f846e4f4b158a8d26681707f4338495bc7ab68151d7f7679cc5e56202dd3da0d356da007a7c28cb0b780418f4f3246769972d6feaa8f610c7d1e7ecf6a
#Database
spring.datasource.url=jdbc:postgresql://localhost:5432/nvtDatabase
spring.datasource.username=postgres
spring.datasource.password=Miroslav02
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.ejb.entity_class_scan_package=com.ftn.sbnz.model.models