// security.drl

package security;
import com.ftn.sbnz.model.models.User;
import com.ftn.sbnz.model.models.SuspicionLevel;
import com.ftn.sbnz.model.models.Order;
import com.ftn.sbnz.model.models.Address;
import com.ftn.sbnz.model.models.OrderStatus;
import com.ftn.sbnz.model.models.CreditCard;
import com.ftn.sbnz.model.models.IPAddress
import java.time.Instant;
global com.ftn.sbnz.model.util.SecurityUtil securityUtil;

rule "Flag new account with more than 1 promo code"
    when
        $account : User(
            newAccount == true,
            activePromoCodes.size() > 1,
            suspicionLevel == SuspicionLevel.VALID
        )
    then
        $account.setSuspicionLevel(SuspicionLevel.SUSPICIOUS);
        update($account);
end

rule "Flag new account if email is temporary"
    when
        $account : User(
        suspicionLevel == SuspicionLevel.VALID,
        newAccount == true
        )
        eval(securityUtil.isMailTemporary($account.getEmail()))
    then
        $account.setSuspicionLevel(SuspicionLevel.SUSPICIOUS);
        update($account);
end

rule "Penalize order cancelling -> User Level 2"
    when
        $account : User(suspicionLevel == SuspicionLevel.VALID)
        $order : Order(
            customerAccount == $account,
            status == OrderStatus.CANCELLED
        )
    then
        $account.setSuspicionLevel(SuspicionLevel.SUSPICIOUS);
        update($account);
end

rule "New account, address is suspicious -> User Level 2"
    when
        $account : User(
            suspicionLevel == SuspicionLevel.VALID,
            address != null
        )
        $address : Address(
            id == $account.address.id,
            suspicious == true
        )
    then
        $account.setSuspicionLevel(SuspicionLevel.SUSPICIOUS);
        update($account);
end

rule "CreditCard is suspicious -> User Level 2"
    when
        $account : User(
            suspicionLevel == SuspicionLevel.VALID,
            cardNumber != null
        )
        $card : CreditCard(
            id == $account.cardNumber.id,
            suspicious == true
        )
    then
        $account.setSuspicionLevel(SuspicionLevel.SUSPICIOUS);
        update($account);
end

rule "Card used on 3+ accounts -> User Level 2 & Flag Card"
    when
        $account : User(
            newAccount == true,
            suspicionLevel == SuspicionLevel.VALID,
            cardNumber != null
        )
        $card : CreditCard(
            id == $account.cardNumber.id,
            numberOfAccounts >= 3,
            suspicious == false
        )
    then
        $account.setSuspicionLevel(SuspicionLevel.SUSPICIOUS);
        update($account);
        $card.setSuspicious(true);
        update($card);
end

rule "Order on suspicious IP address -> User Level 2"
    when
        $account : User(suspicionLevel == SuspicionLevel.VALID)
        $ipAddress : IPAddress(suspicious == true)
        $order : Order(
            user == $account,
            ipAddress == $ipAddress
        )
    then
        $account.setSuspicionLevel(SuspicionLevel.SUSPICIOUS);
        update($account);
end
rule "Penalize order cancelling -> User Level 3"
    when
        $account : User(suspicionLevel == SuspicionLevel.SUSPICIOUS)
        $order : Order(
            customerAccount == $account,
            status == OrderStatus.CANCELLED
        )
    then
        $account.setSuspicionLevel(SuspicionLevel.MALICIOUS);
        $account.setSuspended(true);
        $account.setBlockExpirationDate(securityUtil.getShortBlockExpiration());
        update($account);
end
rule "Address changed while suspicious -> User Level 3"
    when
        $account : User(
            suspicionLevel == SuspicionLevel.SUSPICIOUS,
            hasChangedAddress == true)
    then
        $account.setSuspicionLevel(SuspicionLevel.MALICIOUS);
        $account.setHasChangedAddress(false);
        update($account);
end

rule "Block suspicious new account with more than 1 promo code"
    when
        $account : User(
            newAccount == true,
            activePromoCodes.size() > 1,
            suspicionLevel == SuspicionLevel.SUSPICIOUS
        )
    then
        $account.setSuspended(true);
        $account.setBlockExpirationDate(securityUtil.getShortBlockExpiration());
        update($account);
end

rule "Address changed while malicious"
    when
        $account : User(
            suspicionLevel == SuspicionLevel.MALICIOUS,
            hasChangedAddress == true)
    then
      $account.setSuspended(true);
      $account.setBlockExpirationDate(securityUtil.getShortBlockExpiration());
      update($account);
end

rule "Order cancelling while suspicious"
    when
        $account : User(suspicionLevel == SuspicionLevel.MALICIOUS)
        $order : Order(
            customerAccount == $account,
            status == OrderStatus.CANCELLED
        )
    then
        $account.setSuspended(true);
        $account.setBlockExpirationDate(securityUtil.getShortBlockExpiration());
        update($account);
end

rule "Accumulate Spent > 3000 (Level 2) -> Level 1"
    no-loop true
    agenda-group "promotion_level_1"
    when
        $account : User(
            suspicionLevel == SuspicionLevel.SUSPICIOUS,
            suspended == false,
            $lastReset : lastAccumulationResetDate
        )

        $totalSpent : Double() from accumulate (
            Order(
                customerAccount == $account,
                status == OrderStatus.DELIVERED,
                $price : orderPrice,
                creationDate > $lastReset
            ),
            sum($price)
        )

        eval($totalSpent > 3000.0)
    then
        $account.setSuspicionLevel(SuspicionLevel.VALID);
        $account.setLastAccumulationResetDate(Instant.now());
        update($account);
end

rule "Accumulate Spent > 5000 (Level 3) -> Level 1"
    no-loop true
    agenda-group "promotion_level_1"
    when
        $account : User(
            suspicionLevel == SuspicionLevel.MALICIOUS,
            suspended == false,
            $lastReset : lastAccumulationResetDate
        )

        $totalSpent : Double() from accumulate (
            Order(
                customerAccount == $account,
                status == OrderStatus.DELIVERED,
                $price : orderPrice,
                creationDate > $lastReset
            ),
            sum($price)
        )

        eval($totalSpent > 5000.0)
    then
        $account.setSuspicionLevel(SuspicionLevel.VALID);
        $account.setLastAccumulationResetDate(Instant.now());
        update($account);
end